name: Auto Merge PR

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    if: github.event.pull_request.labels.*.name == 'auto-merge'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Auto Merge PR
        uses: ahmadnassri/action-auto-merge-dependabot@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: merge
